### ISSUE TITLE
能支持微信小程序webview 调试工具吗？

### ISSUE THREAD

**Issue by qinfangge** [whistle-plugins/whistle.inspect#10]
调试工具我看能在浏览器上出现，但是在微信嵌套的小程序 webview 里没有

**Comment by avwo** [comment]
只要是网页都可以，看看能抓到webview的请求吗

**Comment by mocobk** [comment]
> 只要是网页都可以，看看能抓到webview的请求吗

试过不太行，小程序静态文件是缓存的，没有请求

**Comment by avwo** [comment]
清下缓存再请求
