### ISSUE TITLE
注入位置能提前吗

### ISSUE THREAD

**Issue by sunmaer** [whistle-plugins/whistle.inspect#5]
现在 vConsole 是注入在 body 结束标签前，如果在注入前发生了 js 错误，就会导致注入失败，想问下这个注入时机能提前吗，注入 到 head 里面

**Comment by avwo** [comment]
已更新，重新安装下插件

**Comment by sunmaer** [comment]
> 已更新，重新安装下插件

已升级，很好用，感谢大佬
