### ISSUE TITLE
Chrome/43.0.2357.134  Not show vConsole

### ISSUE THREAD

**Issue by Hrealm** [whistle-plugins/whistle.inspect#6]
Chrome/43.0.2357.134

Uncaught ReferenceError: Proxy is not defined

![image](https://user-images.githubusercontent.com/28807967/159416560-28b21ded-bbe1-47cd-86cd-f41700cc40c4.png)

**Comment by avwo** [comment]
Chrome 版本太低，很多第三方组件都不支持了。

**Comment by Hrealm** [comment]
或者有没有 whistle.inspect 哪个版本对应  vConsole v3.2.2 ？

**Comment by avwo** [comment]
用 `1.1.0` 看下

**Comment by Hrealm** [comment]
> 用 `1.1.0` 看下
好的，谢谢
